### ISSUE TITLE
Chokes on SmartyPrint

### ISSUE THREAD

**Issue by wyager** [agrafix/HSmarty#3]
Hey there,

I know this is an older project, but hopefully you can help me figure out what's going on here. For some reason, it seems to be failing to parse SmartyPrints. For example, using 

```
{* foo *}
bar
```

is fine, but

```
{* foo *}
bar
{baz}
```

is not. This fails with `*** Exception: user error (endOfInput)`

Any ideas?

**Comment by agrafix** [comment]
I don't think `{baz}` is valid smarty? Should it not be `{$baz}`?

**Comment by wyager** [comment]
That is 100% entirely possible. I was given some smarty files from an older codebase, so they may have been using some formatted that allowed out-of-spec smarty files. Let me check and get back to you.

**Comment by wyager** [comment]
Cool, you were right; adding a `$` fixed it. Thanks!
